using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Spelling.Rules
{
	class Rule11 : Rule
	{
		public string[] van =
		{
			"ang", "áng", "àng", "ảng", "ãng", "ạng",
			"ăng", "ắng", "ằng", "ẳng", "ẵng", "ặng",
			"âng", "ấng", "ầng", "ẩng", "ẫng", "ậng",
			"iêng", "iếng", "iềng", "iểng", "iễng", "iệng",
			"ong", "óng", "òng", "ỏng", "õng", "ọng",
			"oang", "oáng", "oàng", "oảng", "oãng", "oạng",
			"oăng", "oắng", "oằng", "oẳng", "oẵng", "oặng",
			"ông", "ống", "ồng", "ổng", "ỗng", "ộng",
			"ung", "úng", "ùng", "ủng", "ũng", "ụng",
			"uâng", "uấng", "uầng", "uẩng", "uẫng", "uậng",
			"uông", "uống", "uồng", "uổng", "uỗng", "uộng",
			"ưng", "ứng", "ừng", "ửng", "ững", "ựng",
			"ương", "ướng", "ường", "ưởng", "ưỡng", "ượng",
			"anh", "ánh", "ành", "ảnh", "ãnh", "ạnh",
			"inh", "ính", "ình", "ỉnh", "ĩnh", "ịnh",
			"ênh", "ếnh", "ềnh", "ểnh", "ễnh", "ệnh",
			"oanh", "oánh", "oành", "oảnh", "oãnh", "oạnh",
			"uênh", "uếnh", "uềnh", "uểnh", "uễnh", "uệnh",
			"uynh", "uýnh", "uỳnh", "uỷnh", "uỹnh", "uỵnh",
			"ách", "ạch",
			"ích", "ịch",
			"ếch", "ệch",
			"oách", "oạch",
			"uếch", "uệch",
			"uých", "uỵch",
			"ác", "ạc",
			"ắc", "ặc",
			"ấc", "ậc",
			"éc", "ẹc",
			"iếc", "iệc",
			"óc", "ọc",
			"oác", "oạc",
			"oắc", "oặc",
			"ốc", "ộc",
			"úc", "ục",
			"uốc", "uộc",
			"ức", "ực",
			"ước", "ược",
			"am", "ám", "àm", "ảm", "ãm", "ạm",
			"ăm", "ắm", "ằm", "ẳm", "ẵm", "ặm",
			"âm", "ấm", "ầm", "ẩm", "ẫm", "ậm",
			"em", "ém", "èm", "ẻm", "ẽm", "ẹm",
			"êm", "ếm", "ềm", "ểm", "ễm", "ệm",
			"im", "ím", "ìm", "ỉm", "ĩm", "ịm",
			"iêm", "iếm", "iềm", "iểm", "iễm", "iệm",
			"om", "óm", "òm", "ỏm", "õm", "ọm",
			"oam", "oám", "oàm", "oảm", "oãm", "oạm",
			"oăm", "oắm", "oằm", "oẳm", "oẵm", "oặm",
			"ôm", "ốm", "ồm", "ổm", "ỗm", "ộm",
			"ơm", "ớm", "ờm", "ởm", "ỡm", "ợm",
			"um", "úm", "ùm", "ủm", "ũm", "ụm",
			"uôm", "uốm", "uồm", "uổm", "uỗm", "uộm",
			"ưm", "ứm", "ừm", "ửm", "ữm", "ựm",
			"ươm", "ướm", "ườm", "ưởm", "ưỡm", "ượm",
			"an", "án", "àn", "ản", "ãn", "ạn",
			"ăn", "ắn", "ằn", "ẳn", "ẵn", "ặn",
			"ân", "ấn", "ần", "ẩn", "ẫn", "ận",
			"en", "én", "èn", "ẻn", "ẽn", "ẹn",
			"ên", "ến", "ền", "ển", "ễn", "ện",
			"in", "ín", "ìn", "ỉn", "ĩn", "ịn",
			"iên", "iến", "iền", "iển", "iễn", "iện",
			"on", "ón", "òn", "ỏn", "õn", "ọn",
			"oan", "oán", "oàn", "oản", "oãn", "oạn",
			"oăn", "oắn", "oằn", "oẳn", "oẵn", "oặn",
			"oen", "oén", "oèn", "oẻn", "oẽn", "oẹn",
			"ôn", "ốn", "ồn", "ổn", "ỗn", "ộn",
			"ơn", "ớn", "ờn", "ởn", "ỡn", "ợn",
			"un", "ún", "ùn", "ủn", "ũn", "ụn",
			"uân", "uấn", "uần", "uẩn", "uẫn", "uận",
			"uôn", "uốn", "uồn", "uổn", "uỗn", "uộn",
			"uyên", "uyến", "uyền", "uyển", "uyễn", "uyện",
			"ưn", "ứn", "ừn", "ửn", "ữn", "ựn",
			"ươn", "ướn", "ườn", "ưởn", "ưỡn", "ượn",
			"yn", "ýn", "ỳn", "ỷn", "ỹn", "ỵn",
			"yên", "yến", "yền", "yển", "yễn", "yện",
			"áp", "ạp",
			"ắp", "ặp",
			"ấp", "ập",
			"ép", "ẹp",
			"ếp", "ệp",
			"íp", "ịp",
			"iếp", "iệp",
			"óp", "ọp",
			"oáp", "oạp",
			"ốp", "ộp",
			"ớp", "ợp",
			"úp", "ụp",
			"uýp", "uỵp",
			"uốp", "uộp",
			"ướp", "ượp",
			"ít", "ịt",
			"iết", "iệt",
			"ứt", "ựt",
			"ướt", "ượt",
			"út", "ụt",
			"uất", "uật",
			"uốt", "uột",
			"uýt", "uỵt",
			"uyết", "uyệt",
			"ết", "ệt",
			"ớt", "ợt",
			"ất", "ật",
			"ốt", "ột",
			"ét", "ẹt",
			"át", "ạt",
			"ắt", "ặt",
			"ót", "ọt",
			"oắt", "oặt",
			"oét", "oẹt",
			"ýt", "ỵt",
			"a", "á", "à", "ả", "ã", "ạ",
			"ai", "ái", "ài", "ải", "ãi", "ại",
			"ao", "áo", "ào", "ảo", "ão", "ạo",
			"au", "áu", "àu", "ảu", "ãu", "ạu",
			"ay", "áy", "ày", "ảy", "ãy", "ạy",
			"âu", "ấu", "ầu", "ẩu", "ẫu", "ậu",
			"ây", "ấy", "ầy", "ẩy", "ẫy", "ậy",
			"e", "é", "è", "ẻ", "ẽ", "ẹ",
			"eo", "éo", "èo", "ẻo", "ẽo", "ẹo",
			"ê", "ế", "ề", "ể", "ễ", "ệ",
			"êu", "ếu", "ều", "ểu", "ễu", "ệu",
			"i", "í", "ì", "ỉ", "ĩ", "ị",
			"ia", "ía", "ìa", "ỉa", "ĩa", "ịa",
			"iu", "íu", "ìu", "ỉu", "ĩu", "ịu",
			"o", "ó", "ò", "ỏ", "õ", "ọ",
			"oa", "óa", "òa", "ỏa", "õa", "ọa",
			"oe", "óe", "òe", "ỏe", "õe", "ọe",
			"oi", "ói", "òi", "ỏi", "õi", "ọi",
			"ô", "ố", "ồ", "ổ", "ỗ", "ộ",
			"ôi", "ối", "ồi", "ổi", "ỗi", "ội",
			"ơ", "ớ", "ờ", "ở", "ỡ", "ợ",
			"ơi", "ới", "ời", "ởi", "ỡi", "ợi",
			"u", "ú", "ù", "ủ", "ũ", "ụ",
			"ua", "úa", "ùa", "ủa", "ũa", "ụa",
			"uê", "uế", "uề", "uể", "uễ", "uệ",
			"ui", "úi", "ùi", "ủi", "ũi", "ụi",
			"uơ", "uớ", "uờ", "uở", "uỡ", "uợ",
			"uy", "úy", "ùy", "ủy", "ũy", "ụy",
			"ư", "ứ", "ừ", "ử", "ữ", "ự",
			"ưa", "ứa", "ừa", "ửa", "ữa", "ựa",
			"ưi", "ứi", "ừi", "ửi", "ữi", "ựi",
			"ưu", "ứu", "ừu", "ửu", "ữu", "ựu",
			"y", "ý", "ỳ", "ỷ", "ỹ", "ỵ",
			"yêu", "yếu", "yều", "yểu", "yễu", "yệu",
			"iêu", "iếu", "iều", "iểu", "iễu", "iệu",
			"ươi", "ưới", "ười", "ưởi", "ưỡi", "ượi",
			"oeo", "oéo", "oèo", "oẻo", "oẽo", "oẹo",
			"oai", "oái", "oài", "oải", "oãi", "oại",
			"uôi", "uối", "uồi", "uổi", "uỗi", "uội",
			"uây", "uấy", "uầy", "uẩy", "uẫy", "uậy",
			"oay", "oáy", "oày", "oảy", "oãy", "oạy",
			"yết", "yệt",
			"oát", "oạt",
			"ươu", "ướu", "ườu", "ưởu", "ưỡu", "ượu"
		};

		public override bool Check(Word word)
		{
			if (word.IsLastPresent() && !van.Contains(word.last))
			{
				return false;
			}

			return true;
		}
	}
}
